# Generated by Django 4.2.29 on 2026-06-29 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospitals", "0002_ward_bed"),
        ("patients", "0004_alter_patientalert_label_alter_patientalert_reaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_for", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("outpatient", "Outpatient Consultation"),
                            ("follow_up", "Follow-Up"),
                            ("procedure", "Procedure / Intervention"),
                            ("lab", "Laboratory Visit"),
                            ("emergency", "Emergency"),
                        ],
                        default="outpatient",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason for visit")),
                ("notes", models.TextField(blank=True, verbose_name="Administrative notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="The doctor or nurse the patient is seeing.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments_as_provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "ordering": ["scheduled_for"],
            },
        ),
    ]
