# Generated by Django 4.2.30 on 2026-07-01 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0002_index_appointment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="appointment_duration_positive",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_hospital_schedule_idx",
        ),
    ]
