# Generated by Django 4.2.30 on 2026-07-14 03:07

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_appointment_appointment_duration_positive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=core.fields.EncryptedTextField(blank=True, verbose_name='Administrative notes'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=core.fields.EncryptedTextField(blank=True, verbose_name='Reason for visit'),
        ),
    ]
