# Generated by Django 4.2.29 on 2026-06-29 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospitals", "0002_ward_bed"),
        ("patients", "0004_alter_patientalert_label_alter_patientalert_reaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(verbose_name="Reason / clinical summary")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("stat", "STAT (Emergency)"),
                        ],
                        default="routine",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "status_notes",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection, acceptance notes, etc.",
                        verbose_name="Status notes",
                    ),
                ),
                (
                    "from_hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_referrals",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "from_provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="patients.patient",
                    ),
                ),
                (
                    "to_hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_referrals",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "to_provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific receiving doctor if known; otherwise any clinician at the to_hospital.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "ordering": ["-created_at"],
            },
        ),
    ]
