# Generated by Django 4.2.30 on 2026-07-01 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0002_index_referral"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="referral",
            name="referral_to_hospital_status_idx",
        ),
    ]
