# Generated by Django 4.2.29 on 2026-06-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_mfa_trust_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("hospital_admin", "Hospital Admin"),
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("lab_technician", "Lab Technician"),
                    ("receptionist", "Receptionist"),
                ],
                default="receptionist",
                max_length=20,
            ),
        ),
    ]
