# Generated by Django 4.2.29 on 2026-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="attempts",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of failed verification attempts. Burned after 5."
            ),
        ),
    ]
