# Generated by Django 4.2.30 on 2026-07-01 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0002_check_shift_ended_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shiftrecord",
            name="shiftrecord_ended_after_started",
        ),
    ]
