# Generated by Django 4.2.29 on 2026-07-02 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shifts", "0003_remove_shiftrecord_shiftrecord_ended_after_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="handover",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="handover",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handovers_acknowledged",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
