# Generated by Django 4.2.30 on 2026-06-26 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                ("actor_role", models.CharField(blank=True, max_length=20)),
                ("actor_hospital", models.CharField(blank=True, max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("VIEW_PATIENT", "View Patient"),
                            ("CREATE_PATIENT", "Create Patient"),
                            ("UPDATE_PATIENT", "Update Patient"),
                            ("VIEW_ENCOUNTER", "View Encounter"),
                            ("CREATE_ENCOUNTER", "Create Encounter"),
                            ("CREATE_DIAGNOSIS", "Create Diagnosis"),
                            ("CREATE_PRESCRIPTION", "Create Prescription"),
                            ("CREATE_LAB_RESULT", "Create Lab Result"),
                            ("ACCESS_DENIED", "Access Denied"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=50)),
                (
                    "patient_nhid",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="Patient NHID"
                    ),
                ),
                (
                    "is_cross_hospital",
                    models.BooleanField(
                        default=False,
                        help_text="True if accessing clinician's hospital differs from the record's origin hospital.",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
