# Generated by Django 4.2.30 on 2026-06-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="prev_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="row_hash",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("VIEW_PATIENT", "View Patient"),
                    ("CREATE_PATIENT", "Create Patient"),
                    ("UPDATE_PATIENT", "Update Patient"),
                    ("VIEW_ENCOUNTER", "View Encounter"),
                    ("CREATE_ENCOUNTER", "Create Encounter"),
                    ("CREATE_DIAGNOSIS", "Create Diagnosis"),
                    ("CREATE_PRESCRIPTION", "Create Prescription"),
                    ("CREATE_LAB_RESULT", "Create Lab Result"),
                    ("ACCESS_DENIED", "Access Denied"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("MFA_ENROLLED", "MFA Enrolled"),
                    ("MFA_VERIFIED", "MFA Verified"),
                    ("MFA_REMOVED", "MFA Device Removed"),
                    ("BREAK_GLASS", "Break-Glass Override"),
                    ("TREATMENT_REL_STARTED", "Treatment Relationship Started"),
                    ("CONSENT_GRANTED", "Patient Consent Granted"),
                ],
                max_length=30,
            ),
        ),
    ]
