# Generated by Django 4.2.30 on 2026-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0005_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("VIEW_PATIENT", "View Patient"),
                    ("CREATE_PATIENT", "Create Patient"),
                    ("UPDATE_PATIENT", "Update Patient"),
                    ("VIEW_ENCOUNTER", "View Encounter"),
                    ("CREATE_ENCOUNTER", "Create Encounter"),
                    ("CREATE_DIAGNOSIS", "Create Diagnosis"),
                    ("CREATE_PRESCRIPTION", "Create Prescription"),
                    ("CREATE_LAB_RESULT", "Create Lab Result"),
                    ("ACCESS_DENIED", "Access Denied"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("MFA_ENROLLED", "MFA Enrolled"),
                    ("MFA_VERIFIED", "MFA Verified"),
                    ("MFA_REMOVED", "MFA Device Removed"),
                    ("SEARCH_PATIENT", "Patient Search"),
                    ("CREATE_ALERT", "Alert/Allergy Created"),
                    ("DEACTIVATE_ALERT", "Alert/Allergy Deactivated"),
                    ("BREAK_GLASS", "Break-Glass Override"),
                    ("TREATMENT_REL_STARTED", "Treatment Relationship Started"),
                    ("CONSENT_GRANTED", "Patient Consent Granted"),
                    ("RECOVERY_CODES_REGENERATED", "Recovery Codes Regenerated"),
                    ("SESSIONS_REVOKED", "Sessions Revoked (Sign Out Everywhere)"),
                    ("STAFF_DEACTIVATED", "Staff Account Deactivated"),
                    ("STAFF_ACTIVATED", "Staff Account Activated"),
                    ("CREATE_VITAL", "Vital Signs Recorded"),
                    ("CREATE_LAB_ORDER", "Lab Order Created"),
                    ("UPDATE_LAB_ORDER", "Lab Order Updated"),
                    ("ADMINISTER_MEDICATION", "Medication Administered"),
                    ("CREATE_APPOINTMENT", "Appointment Created"),
                    ("UPDATE_APPOINTMENT", "Appointment Status Updated"),
                    ("CREATE_REFERRAL", "Referral Created"),
                    ("UPDATE_REFERRAL", "Referral Status Updated"),
                    ("START_SHIFT", "Shift Started"),
                    ("END_SHIFT", "Shift Ended"),
                    ("CREATE_HANDOVER", "Handover Note Created"),
                    ("AI_QUERY", "AI Patient Query"),
                    ("EXPORT_PDF", "Patient PDF Export"),
                    ("VALIDATE_AUDIT_CHAIN", "Audit Chain Validated"),
                    ("RESET_STAFF_PASSWORD", "Staff Password Reset"),
                ],
                max_length=30,
            ),
        ),
    ]
