# Generated by Django 4.2.30 on 2026-07-01 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0007_index_action_is_cross_hospital"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Audit Log Review",
                "verbose_name_plural": "Audit Log Reviews",
            },
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="auditlog_action_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="auditlog_cross_hospital_idx",
        ),
        migrations.AddField(
            model_name="auditlogreview",
            name="audit_log",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="audit.auditlog",
            ),
        ),
        migrations.AddField(
            model_name="auditlogreview",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
