# Generated by Django 4.2.30 on 2026-06-26 02:15

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("OPD", "Outpatient (OPD)"),
                            ("IPD", "Inpatient (IPD)"),
                            ("EMRG", "Emergency"),
                            ("FU", "Follow-up"),
                            ("TM", "Telemedicine"),
                        ],
                        default="OPD",
                        max_length=4,
                    ),
                ),
                (
                    "chief_complaint",
                    core.fields.EncryptedTextField(
                        verbose_name="Chief complaint / presenting problem"
                    ),
                ),
                (
                    "notes",
                    core.fields.EncryptedTextField(blank=True, verbose_name="Clinical notes"),
                ),
                (
                    "created_at_hospital",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to="hospitals.hospital",
                        verbose_name="Hospital (encounter location)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounters",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encounter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drug_name",
                    core.fields.EncryptedCharField(
                        max_length=200, verbose_name="Drug / Medication name"
                    ),
                ),
                (
                    "dosage",
                    core.fields.EncryptedCharField(max_length=100, verbose_name="Dosage & route"),
                ),
                (
                    "frequency",
                    core.fields.EncryptedCharField(
                        max_length=100, verbose_name="Frequency / duration"
                    ),
                ),
                (
                    "instructions",
                    core.fields.EncryptedTextField(
                        blank=True, verbose_name="Additional instructions"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="records.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_name",
                    core.fields.EncryptedCharField(max_length=200, verbose_name="Test name"),
                ),
                ("result_value", core.fields.EncryptedTextField(verbose_name="Result / findings")),
                (
                    "reference_range",
                    models.CharField(blank=True, max_length=100, verbose_name="Reference range"),
                ),
                ("is_abnormal", models.BooleanField(default=False)),
                (
                    "performed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date/time performed"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_results_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="records.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Result",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "icd_code",
                    models.CharField(blank=True, max_length=20, verbose_name="ICD-10 code"),
                ),
                (
                    "description",
                    core.fields.EncryptedTextField(verbose_name="Diagnosis description"),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnoses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="records.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
                "ordering": ["-created_at"],
            },
        ),
    ]
