# Generated by Django 4.2.30 on 2026-06-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="snomed_code",
            field=models.CharField(
                blank=True,
                help_text="Optional SNOMED CT concept ID for interoperability.",
                max_length=20,
                verbose_name="SNOMED CT code",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="loinc_code",
            field=models.CharField(
                blank=True,
                help_text="Optional LOINC code for structured lab interoperability, e.g. 2160-0 (Creatinine).",
                max_length=20,
                verbose_name="LOINC code",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="rxnorm_code",
            field=models.CharField(
                blank=True,
                help_text="Optional RxNorm CUI for structured medication interoperability.",
                max_length=20,
                verbose_name="RxNorm code",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="icd_code",
            field=models.CharField(
                blank=True,
                help_text="ICD-10-CM code, e.g. J18.9 (Pneumonia, unspecified).",
                max_length=20,
                verbose_name="ICD-10 code",
            ),
        ),
    ]
