# Generated by Django 4.2.29 on 2026-06-29 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0004_alter_patientalert_label_alter_patientalert_reaction"),
        ("records", "0002_diagnosis_snomed_code_labresult_loinc_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Temperature (°C)",
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Heart rate (bpm)"
                    ),
                ),
                (
                    "respiratory_rate",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Respiratory rate (breaths/min)"
                    ),
                ),
                (
                    "bp_systolic",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="BP systolic (mmHg)"
                    ),
                ),
                (
                    "bp_diastolic",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="BP diastolic (mmHg)"
                    ),
                ),
                (
                    "spo2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="SpO2 (%)",
                    ),
                ),
                (
                    "pain_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pain score (0–10)"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Height (cm)",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="records.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vitals",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vitals_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vital Sign",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicationAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_time", models.DateTimeField()),
                ("administered_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "Due"),
                            ("given", "Given"),
                            ("held", "Held"),
                            ("refused", "Refused by Patient"),
                            ("missed", "Missed"),
                        ],
                        default="due",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medications_administered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrations",
                        to="records.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication Administration",
                "verbose_name_plural": "Medication Administrations",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("test_name", models.CharField(max_length=200, verbose_name="Test name")),
                (
                    "loinc_code",
                    models.CharField(blank=True, max_length=20, verbose_name="LOINC code"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("stat", "STAT (Immediate)"),
                        ],
                        default="routine",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resulted", "Resulted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(blank=True, verbose_name="Clinical notes for lab"),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_orders",
                        to="records.encounter",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="labresult",
            name="order",
            field=models.OneToOneField(
                blank=True,
                help_text="The originating order, if placed through the system.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result",
                to="records.laborder",
            ),
        ),
    ]
