# Generated by Django 4.2.30 on 2026-07-01 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0004_index_encounter_check_vitals"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vitalsign",
            name="vitalsign_temperature_range",
        ),
        migrations.RemoveConstraint(
            model_name="vitalsign",
            name="vitalsign_heart_rate_range",
        ),
        migrations.RemoveConstraint(
            model_name="vitalsign",
            name="vitalsign_bp_systolic_range",
        ),
        migrations.RemoveConstraint(
            model_name="vitalsign",
            name="vitalsign_bp_diastolic_range",
        ),
        migrations.RemoveConstraint(
            model_name="vitalsign",
            name="vitalsign_spo2_range",
        ),
        migrations.RemoveConstraint(
            model_name="vitalsign",
            name="vitalsign_pain_score_range",
        ),
        migrations.RemoveIndex(
            model_name="encounter",
            name="encounter_patient_created_idx",
        ),
    ]
