# Generated by Django 4.2.29 on 2026-07-02 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0004_alter_patientalert_label_alter_patientalert_reaction"),
        ("records", "0005_remove_vitalsign_vitalsign_temperature_range_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="patient_documents/%Y/%m/")),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Original file name"),
                ),
                (
                    "file_type",
                    models.CharField(blank=True, max_length=100, verbose_name="MIME type"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="File size (bytes)"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Description"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Document",
                "ordering": ["-created_at"],
            },
        ),
    ]
