# Generated by Django 4.2.30 on 2026-07-14 03:07

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_encounter_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='clinical_notes',
            field=core.fields.EncryptedTextField(blank=True, verbose_name='Clinical notes for lab'),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='notes',
            field=core.fields.EncryptedTextField(blank=True),
        ),
    ]
