# Generated by Django 4.2.29 on 2026-09-08 00:53

import core.fields
from django.db import migrations, models
import records.validators


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_encounter_status_prescription_discontinued_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='icd_code_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='HMAC-SHA256 blind index of icd_code for exact-match querying.', max_length=64),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='snomed_code_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='HMAC-SHA256 blind index of snomed_code for exact-match querying.', max_length=64),
        ),
        migrations.AddField(
            model_name='laborder',
            name='loinc_code_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='HMAC-SHA256 blind index of loinc_code for exact-match querying.', max_length=64),
        ),
        migrations.AddField(
            model_name='laborder',
            name='test_name_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='HMAC-SHA256 blind index of test_name for exact-match querying.', max_length=64),
        ),
        migrations.AddField(
            model_name='labresult',
            name='loinc_code_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='HMAC-SHA256 blind index of loinc_code for exact-match querying.', max_length=64),
        ),
        migrations.AddField(
            model_name='labresult',
            name='test_name_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='HMAC-SHA256 blind index of test_name for exact-match querying.', max_length=64),
        ),
        migrations.AddField(
            model_name='prescription',
            name='rxnorm_code_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='HMAC-SHA256 blind index of rxnorm_code for exact-match querying.', max_length=64),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='icd_code',
            field=core.fields.EncryptedCharField(blank=True, help_text='ICD-10-CM code, e.g. J18.9 (Pneumonia, unspecified).', max_length=20, validators=[records.validators.validate_icd10], verbose_name='ICD-10 code'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='snomed_code',
            field=core.fields.EncryptedCharField(blank=True, help_text='Optional SNOMED CT concept ID for interoperability.', max_length=20, validators=[records.validators.validate_snomed], verbose_name='SNOMED CT code'),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='loinc_code',
            field=core.fields.EncryptedCharField(blank=True, help_text='Optional LOINC code for structured lab interoperability.', max_length=20, validators=[records.validators.validate_loinc], verbose_name='LOINC code'),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='test_name',
            field=core.fields.EncryptedCharField(max_length=200, verbose_name='Test name'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='loinc_code',
            field=core.fields.EncryptedCharField(blank=True, help_text='Optional LOINC code for structured lab interoperability, e.g. 2160-0 (Creatinine).', max_length=20, validators=[records.validators.validate_loinc], verbose_name='LOINC code'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rxnorm_code',
            field=core.fields.EncryptedCharField(blank=True, help_text='Optional RxNorm CUI for structured medication interoperability.', max_length=20, validators=[records.validators.validate_rxnorm], verbose_name='RxNorm code'),
        ),
    ]
