# Generated by Django 4.2.29 on 2026-09-08 01:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_encrypt_clinical_codes_and_blind_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='bp_diastolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)], verbose_name='BP diastolic (mmHg)'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='bp_systolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='BP systolic (mmHg)'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Heart rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='pain_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Pain score (0–10)'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='spo2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('50.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='SpO2 (%)'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('45.0'))], verbose_name='Temperature (°C)'),
        ),
        migrations.AddConstraint(
            model_name='vitalsign',
            constraint=models.CheckConstraint(check=models.Q(('temperature__isnull', True), models.Q(('temperature__gte', 30.0), ('temperature__lte', 45.0)), _connector='OR'), name='vitalsign_temperature_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalsign',
            constraint=models.CheckConstraint(check=models.Q(('heart_rate__isnull', True), models.Q(('heart_rate__gte', 20), ('heart_rate__lte', 300)), _connector='OR'), name='vitalsign_heart_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalsign',
            constraint=models.CheckConstraint(check=models.Q(('bp_systolic__isnull', True), models.Q(('bp_systolic__gte', 50), ('bp_systolic__lte', 250)), _connector='OR'), name='vitalsign_bp_systolic_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalsign',
            constraint=models.CheckConstraint(check=models.Q(('bp_diastolic__isnull', True), models.Q(('bp_diastolic__gte', 30), ('bp_diastolic__lte', 150)), _connector='OR'), name='vitalsign_bp_diastolic_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalsign',
            constraint=models.CheckConstraint(check=models.Q(('spo2__isnull', True), models.Q(('spo2__gte', 50), ('spo2__lte', 100)), _connector='OR'), name='vitalsign_spo2_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalsign',
            constraint=models.CheckConstraint(check=models.Q(('pain_score__isnull', True), models.Q(('pain_score__gte', 0), ('pain_score__lte', 10)), _connector='OR'), name='vitalsign_pain_score_range'),
        ),
    ]
