# Generated by Django 4.2.29 on 2026-09-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_prescription_allergy_override_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Flagged when result represents an immediate life-threatening critical value.', verbose_name='Critical value'),
        ),
    ]
