# Generated by Django 4.2.29 on 2026-09-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_labresult_is_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='confidentiality',
            field=models.CharField(choices=[('normal', 'Normal (Standard Clinical Record)'), ('restricted', 'Restricted (Mental Health, HIV, Sensitive Care)'), ('very_restricted', 'Very Restricted (VIP / Special Category)')], db_index=True, default='normal', help_text='Data sensitivity tier under Act 843 §37 / ISO 22600.', max_length=20),
        ),
        migrations.AddField(
            model_name='encounter',
            name='confidentiality',
            field=models.CharField(choices=[('normal', 'Normal (Standard Clinical Record)'), ('restricted', 'Restricted (Mental Health, HIV, Sensitive Care)'), ('very_restricted', 'Very Restricted (VIP / Special Category)')], db_index=True, default='normal', help_text='Data sensitivity tier under Act 843 §37 / ISO 22600.', max_length=20),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='confidentiality',
            field=models.CharField(choices=[('normal', 'Normal (Standard Clinical Record)'), ('restricted', 'Restricted (Mental Health, HIV, Sensitive Care)'), ('very_restricted', 'Very Restricted (VIP / Special Category)')], db_index=True, default='normal', help_text='Data sensitivity tier under Act 843 §37 / ISO 22600.', max_length=20),
        ),
    ]
