# Generated by Django 4.2.29 on 2026-09-08 12:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0016_diagnosis_confidentiality_encounter_confidentiality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsign",
            name="blood_glucose",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.5")),
                    django.core.validators.MaxValueValidator(Decimal("50.0")),
                ],
                verbose_name="Blood glucose (mmol/L)",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("20.0")),
                    django.core.validators.MaxValueValidator(Decimal("300.0")),
                ],
                verbose_name="Height (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="respiratory_rate",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(80),
                ],
                verbose_name="Respiratory rate (breaths/min)",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.5")),
                    django.core.validators.MaxValueValidator(Decimal("500.0")),
                ],
                verbose_name="Weight (kg)",
            ),
        ),
        migrations.AddConstraint(
            model_name="vitalsign",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("blood_glucose__isnull", True),
                    models.Q(
                        ("blood_glucose__gte", Decimal("0.5")),
                        ("blood_glucose__lte", Decimal("50.0")),
                    ),
                    _connector="OR",
                ),
                name="vitalsign_blood_glucose_range",
            ),
        ),
    ]
