# Generated by Django 4.2.29 on 2026-06-29 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patientalert_label_alter_patientalert_reaction"),
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Short identifier, e.g. W3A, ICU, PEDS", max_length=20
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=0, help_text="Max bed count")),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ward",
                "ordering": ["hospital", "name"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(help_text="Bed identifier, e.g. A1, B3", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("cleaning", "Being Cleaned"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="available",
                        max_length=15,
                    ),
                ),
                (
                    "current_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_bed",
                        to="patients.patient",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="hospitals.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bed",
                "ordering": ["ward", "label"],
                "unique_together": {("ward", "label")},
            },
        ),
    ]
