# Generated by Django 4.2.30 on 2026-07-01 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospitals", "0003_partial_unique_bed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bed",
            name="bed_unique_current_patient",
        ),
    ]
