# Generated by Django 4.2.30 on 2026-06-26 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0002_add_blind_index_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="Null = relationship is still active.", null=True
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Clinical reason for the treatment relationship."
                    ),
                ),
                (
                    "clinician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        help_text="Hospital where this care relationship was established.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_relationships",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_relationships",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Treatment Relationship",
                "verbose_name_plural": "Treatment Relationships",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["clinician", "patient"], name="access_trea_clinici_67d59d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("granted", models.BooleanField(default=True)),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_consents",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Consent",
                "verbose_name_plural": "Patient Consents",
                "ordering": ["-granted_at"],
                "unique_together": {("patient", "hospital")},
            },
        ),
        migrations.CreateModel(
            name="BreakGlassAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Required: clinical justification for this emergency override."
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "mfa_reverified",
                    models.BooleanField(
                        default=False,
                        help_text="True if the clinician re-verified their TOTP code at override time.",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="break_glass_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="break_glass_accesses",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Break-Glass Access",
                "verbose_name_plural": "Break-Glass Accesses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "patient", "expires_at"],
                        name="access_brea_actor_i_607066_idx",
                    )
                ],
            },
        ),
    ]
