# Generated by Django 4.2.29 on 2026-09-08 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access", "0002_alter_breakglassaccess_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakglassaccess",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="break_glass_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
