# Generated by Django 4.2.30 on 2026-06-26 02:15

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import patients.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "universal_id",
                    models.CharField(
                        db_index=True,
                        default=patients.models.generate_nhid,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="National Health ID",
                    ),
                ),
                (
                    "first_name",
                    core.fields.EncryptedCharField(max_length=100, verbose_name="First name"),
                ),
                (
                    "last_name",
                    core.fields.EncryptedCharField(
                        max_length=100, verbose_name="Last name / Surname"
                    ),
                ),
                (
                    "date_of_birth",
                    core.fields.EncryptedCharField(
                        help_text="YYYY-MM-DD", max_length=20, verbose_name="Date of birth"
                    ),
                ),
                (
                    "national_id",
                    core.fields.EncryptedCharField(
                        blank=True, max_length=50, verbose_name="National ID / Passport"
                    ),
                ),
                ("phone", core.fields.EncryptedCharField(blank=True, max_length=20)),
                ("email", core.fields.EncryptedCharField(blank=True, max_length=254)),
                ("address", core.fields.EncryptedTextField(blank=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other / Prefer not to say"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("?", "Unknown"),
                        ],
                        default="?",
                        max_length=3,
                    ),
                ),
                (
                    "registered_at_hospital",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_patients",
                        to="hospitals.hospital",
                        verbose_name="Registering hospital",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-created_at"],
            },
        ),
    ]
