# Generated by Django 4.2.30 on 2026-06-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="name_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="HMAC-SHA256 blind index of 'first_name last_name' (lowercase). Used for exact name lookups without decrypting all rows.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="national_id_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="HMAC-SHA256 blind index of national_id. Used for exact national-ID lookups without decrypting all rows.",
                max_length=64,
            ),
        ),
    ]
