# Generated by Django 4.2.30 on 2026-06-28 21:47

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_patientalert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientalert",
            name="label",
            field=core.fields.EncryptedCharField(
                help_text="E.g. Penicillin, Latex, Contrast dye, Peanuts.",
                max_length=200,
                verbose_name="Substance / description",
            ),
        ),
        migrations.AlterField(
            model_name="patientalert",
            name="reaction",
            field=core.fields.EncryptedTextField(
                blank=True,
                help_text="Describe the observed reaction (optional).",
                verbose_name="Reaction notes",
            ),
        ),
    ]
