# Generated by Django 4.2.30 on 2026-08-10

from django.db import migrations


def populate_search_tokens(apps, schema_editor):
    from core.blind_index import make_blind_index
    from patients.models import Patient as ActivePatient
    from patients.models import PatientSearchToken as ActivePatientSearchToken
    from patients.models import generate_name_trigrams

    for p in ActivePatient.objects.all():
        try:
            tokens = generate_name_trigrams(p.first_name, p.last_name)
            new_hashes = {make_blind_index(tok) for tok in tokens if tok}
            for h in new_hashes:
                ActivePatientSearchToken.objects.get_or_create(patient=p, token_hash=h)
        except Exception:
            pass


def rollback_search_tokens(apps, schema_editor):
    from patients.models import PatientSearchToken as ActivePatientSearchToken

    ActivePatientSearchToken.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_patientsearchtoken"),
    ]

    operations = [
        migrations.RunPython(populate_search_tokens, rollback_search_tokens),
    ]
