# Generated by Django 4.2.30 on 2026-09-07 00:00

import core.fields
from django.db import migrations
import patients.models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_populate_search_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=core.fields.EncryptedCharField(
                help_text="YYYY-MM-DD",
                max_length=20,
                validators=[patients.models.validate_date_of_birth],
                verbose_name="Date of birth",
            ),
        ),
    ]
