# Generated by Django 4.2.29 on 2026-09-08 01:32

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0007_alter_patient_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="universal_id",
            field=models.CharField(
                db_index=True,
                default=patients.models.generate_nhid,
                editable=False,
                max_length=32,
                unique=True,
                verbose_name="National Health ID",
            ),
        ),
    ]
